# Generated by Django 3.2.5 on 2023-01-02 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0002_auto_20230102_1447'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tran',
            name='updated',
        ),
    ]
