# Generated by Django 3.2.5 on 2023-01-02 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0003_remove_tran_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tran',
            name='date',
            field=models.BigIntegerField(),
        ),
    ]
