# Generated by Django 3.2.5 on 2023-01-02 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0005_alter_tran_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tran',
            name='date',
            field=models.BigIntegerField(),
        ),
    ]
