# Generated by Django 3.2.5 on 2023-01-04 11:18

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0008_alter_tran_payees'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tran',
            name='payees',
            field=django_mysql.models.ListCharField(models.CharField(max_length=10), blank=True, max_length=66, null=True, size=6),
        ),
    ]
