# Generated by Django 3.2.5 on 2023-01-04 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0009_alter_tran_payees'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tran',
            name='payees',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
