# Generated by Django 3.2.5 on 2023-01-03 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_user_friends'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='amount_spent',
            field=models.IntegerField(null=True),
        ),
    ]
