# Generated by Django 3.2.5 on 2023-01-04 07:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_user_friends'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='payees',
            field=models.OneToOneField(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='payee', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='friends',
            field=models.ManyToManyField(blank=True, default=None, related_name='friend', to=settings.AUTH_USER_MODEL),
        ),
    ]
