# Generated by Django 3.2.5 on 2023-01-04 07:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20230104_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='payees',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payee', to=settings.AUTH_USER_MODEL),
        ),
    ]
