# Generated by Django 3.2.5 on 2023-01-04 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_auto_20230104_1316'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='payees',
        ),
        migrations.AddField(
            model_name='user',
            name='payees',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
